import homeback from "./images/Background.png"
import Logo from "./images/Logo.png"
import Logo2 from "./images/logo2.png"
import Product1 from "./images/product1.png"
import Product2 from "./images/product2.png"
import Product3 from "./images/product3.png"
import Leaves1 from "./images/leaves1.png"
import Leaves2 from "./images/leaves2.png"
import User1 from "./images/user1.png"
import Rightarrow from "./images/rightarrow.png"
import Leftarrow from "./images/leftarrow.png"
import Emailvector from "./images/emailvector.png"
import Wavector from "./images/wavector.png"
import Insta from "./images/insta.png"
import Youtube from "./images/ytb.png"
import Facebook from "./images/fb.png"
import Twitter from "./images/twit.png"
import Bglogin from "./images/BgLogin.png"
import Bgsignup from "./images/Bgsignup.png"
import BgTroom from "./images/Bgroomteraphy.png"
import Theraphy1 from "./images/therapy1.png"
import Bgkarir from "./images/bgkarir.png" 
import Userimg from "./images/userimg.png"
import Icontas from "./images/icontas.png"
import Iconlokasi from "./images/iconlokasi.png"
import Icondolar from "./images/icondolar.png"
import Iconpengalamankerja from "./images/iconpengalamankerja.png"
import Icondokter from "./images/icondokter.png"
import Iconspeaker from "./images/iconspeaker.png"
import Bglineartes from "./images/bglineartes.png"
import Bgtes from "./images/bgtes.png"
import Tes1 from "./images/tes1.png"
import Tes2 from "./images/tes2.png"
import Tes3 from "./images/tes3.png"
import Bgartikel from "./images/bgartikel.png"
import Imgartikel from "./images/imgartikel.png"
import Artikel1 from "./images/artikel1.png"
import Artikel2 from "./images/artikel2.png"
import Artikel3 from "./images/artikel3.png"
import Artikel4 from "./images/artikel4.png"
import Artikel5 from "./images/artikel5.png"
import Artikel6 from "./images/artikel6.png"

const homebackg = homeback;
const bglogin = Bglogin
const logo = Logo;
const logo2 = Logo2;
const product1 = Product1;
const product2 = Product2;
const product3 = Product3;
const leaves1 = Leaves1;
const leaves2 = Leaves2;
const user1 = User1;
const rightarrow = Rightarrow;
const leftarrow = Leftarrow;
const emailvector = Emailvector;
const wavector = Wavector;
const insta = Insta;
const ytb = Youtube;
const fb = Facebook;
const twit = Twitter;
const bgsignup = Bgsignup;
const btroom = BgTroom;
const therapy1 = Theraphy1;
const bgkarir = Bgkarir;
const userimg = Userimg;
const icontas = Icontas;
const iconlokasi = Iconlokasi;
const icondolar = Icondolar;
const iconpengalamankerja = Iconpengalamankerja;
const icondokter = Icondokter;
const iconspeaker = Iconspeaker;
const bglineartes = Bglineartes;
const bgtes = Bgtes;
const tes1 = Tes1;
const tes2 = Tes2;
const tes3 = Tes3;
const bgartikel = Bgartikel;
const imgartikel = Imgartikel;
const artikel1 = Artikel1;
const artikel2 = Artikel2;
const artikel3 = Artikel3;
const artikel4 = Artikel4;
const artikel5 = Artikel5;
const artikel6 = Artikel6;


export {homebackg,logo,product1,product2,product3,leaves1,leaves2,user1,rightarrow,leftarrow,emailvector,wavector,logo2
        ,insta,ytb,fb,twit,bglogin,bgsignup,btroom,therapy1,bgkarir,userimg,icontas,icondolar,iconlokasi,iconpengalamankerja,
        icondokter,iconspeaker,bglineartes,bgtes,tes1,tes2,tes3,bgartikel,imgartikel,artikel1,artikel2,artikel3,artikel4,artikel5,
        artikel6,
};